moving folder, adding regex for personalID and other small changes
iOSinternshipen/Internship2022TeamPatri pull request #12
Opened 2022-08-04 08:54 UTC by MuresanCoralia

### Summary

### Details

### Metadata
- Ticket link: [Register screen](https://trello.com/c/pihhQ6gH/3-ui-register-screen)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-08-05 05:52 UTC, carmenj commented
When creating a PR, please try to add some info in the summary section about the changes the PR contains.

2022-08-05 05:59 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Auth/Register/RegisterViewController.swift
> +                        }
wrong indentation

2022-08-05 05:59 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Auth/Register/RegisterViewController.swift
> +                        }
It looks like a lot of duplicate code. Can you find a way to avoid/mitigate this?

2022-08-05 10:37 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Auth/Register/RegisterViewController.swift
>              }
would it be an option to add the following code before the validation block and then simply set red color for the needed title?
```
[view2.titleLabel, view3.titleLabel, view5.titleLabel].forEach {
        $0.textColor = UIColor.colorText
 }
```

2022-08-05 11:33 UTC, carmenj commented
Suggestion: since both login and register use the same validation for email and password, I would create a separate validation helper class and use it for both scenarios to avoid duplicate code, which is error prone. 
Otherwise, if, for example, the regex changes, we need to modify it in 2 places.

2022-08-05 11:53 UTC, patriciaghitun requested changes
Please find more suggestive names for these views (view1, view2, ..etc)

2022-08-05 11:53 UTC, patriciaghitun commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Auth/Register/RegisterViewController.swift
> +                view3.titleLabel.textColor = UIColor.colorText
Please find more suitable names for these views

2022-08-08 14:38 UTC, patriciaghitun approved these changes

2022-08-08 14:51 UTC, HVlad1 approved these changes

2022-08-09 06:16 UTC, merged