User model
iOSinternshipen/Internship2022TeamPatri pull request #13
Opened 2022-08-05 13:49 UTC by MuresanCoralia

### Summary

Retrieve data from firebase about a user 

### Details

The structure for users (personal info and grades) (Models/UsersModel)
Retrieving data of one user (personal info and grades) (Networking/Services/RetrieveUserData)

### Metadata
- Ticket link: [Get User data](https://trello.com/c/o0jIGSWf/7-api-get-user-data)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-08-09 06:46 UTC, IgnatCamelia requested changes

2022-08-09 06:46 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/Models/UsersDataModel.swift
> +
remove space

2022-08-09 06:46 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/RetrieveUserData.swift
> +
remove space

2022-08-09 06:46 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/RetrieveUserData.swift
> +                 }
Indentation

2022-08-09 06:46 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/AppDelegate.swift
> +import FirebaseAuth
Why did you add these 2?

2022-08-09 06:58 UTC, MuresanCoralia commented on Internship2022TeamPatri/Internship2022TeamPatri/AppDelegate.swift
> +import FirebaseAuth
import FirebaseFirestore I need for the var db = Firestore.firestore()
import FirebaseAuth I will delete

2022-08-09 07:06 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/RetrieveUserData.swift
> +    func fetchPersonalInfo() {
This method should have a user id parameter so you can get the loggedin user info, not a hardcoded id. For example you can get the current user and use the id from there, and in this case you can rename the function into smth like "fetchCurrentUserInfo" and it should return a user model containing all the data, including the grades.

2022-08-09 07:06 UTC, MunBeniamin requested changes

2022-08-09 07:06 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/RetrieveUserData.swift
> +    func fetchGrades() {
same here, it should return the current user grades as a model. and use this function to complete the user data model from above.

2022-08-09 07:11 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Models/UsersDataModel.swift
> +    let photo: UIImage?
I think this should be string, because in the database we will store the image as string, either as image url string, so it will be a string.

2022-08-09 08:06 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/AppDelegate.swift
> +import FirebaseAuth
Where is that variable?

2022-08-09 08:10 UTC, MuresanCoralia commented on Internship2022TeamPatri/Internship2022TeamPatri/AppDelegate.swift
> +import FirebaseAuth
Only now I see it is about AppDelegate. Sorry. I thought it was about RetrieveUserData. I will delete the extra imports

2022-08-10 08:35 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/RetrieveUserData.swift
> +        guard Auth.auth().currentUser != nil else {return}
You should use guard let here and don't use force unwrap bellow.

2022-08-10 15:40 UTC, closed without merging