Added UICourses implementation and changed files position for UIGrades
iOSinternshipen/Internship2022TeamPatri pull request #14
Opened 2022-08-08 13:44 UTC by eduardcaragea27

### Summary
UICourses and UIGrades
### Details
Added UICourses implementation and changed files position for UIGrades
### Metadata
- Ticket link: [UICourses](https://trello.com/c/UmQWGbeL/6-ui-grades-screen-xibT_KEY)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-08-09 07:06 UTC, iOSinternshipen approved these changes

2022-08-09 08:11 UTC, patriciaghitun approved these changes

2022-08-09 08:22 UTC, MunBeniamin requested changes
You don't need to create a xib for the CustomCollectionViewCell if you write the UI programatically, you can remove the xib and add an init as it is on the "CustomTableViewCell".

2022-08-10 08:34 UTC, MunBeniamin approved these changes
Looks good, nice work!

2022-08-10 08:37 UTC, merged