Feature/user profile
iOSinternshipen/Internship2022TeamPatri pull request #16
Opened 2022-08-10 10:54 UTC by MuresanCoralia

### Summary

Profile Screen (Xib)

### Details

### Metadata
- Ticket link: [Profile Screen](https://trello.com/c/6sSszAJJ/12-ui-profile-screen)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-08-10 13:07 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Models/ColorExtension.swift
> +    static let colorTextProfile = UIColor(red: 0.551, green: 0.542, blue: 0.542, alpha: 1)
wrong indentation

2022-08-10 13:36 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Home/Profile/ProfileViewController.swift
> +            shadowView.layer.shadowRadius = 3
wrong indentation

2022-08-10 13:36 UTC, carmenj commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Home/Profile/ProfileViewController.swift
> +            lbNavTitle.font = lbNavTitle.font.withSize(32)
wrong indentation

2022-08-10 14:37 UTC, carmenj approved these changes

2022-08-11 05:09 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Home/Profile/ProfileViewController.swift
> +    private func configure(){
missing space after method name

2022-08-11 05:12 UTC, MunBeniamin requested changes

2022-08-11 05:12 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Home/Profile/ProfileViewController.swift
> +    @IBAction func logOut(_ sender: Any) {
This should be done on the AuthApiManager, and on the profile page just call the logout method from the manager. The manager should notify the AppDelegate when the user is logged out and there you should call the reset root method which is already implemented.

2022-08-11 16:52 UTC, patriciaghitun approved these changes

2022-08-12 05:52 UTC, MunBeniamin approved these changes

2022-08-12 06:00 UTC, merged