Firebase set up
iOSinternshipen/Internship2022TeamPatri pull request #5
Opened 2022-07-28 12:22 UTC by SaniutaRobert

### Summary

### Details

### Metadata
- Ticket link: [Ticket Name](https://trello.com/c/TICKET_KEY)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-07-28 12:59 UTC, IgnatCamelia approved these changes

2022-07-28 14:41 UTC, MunBeniamin requested changes, later dismissed

2022-07-28 14:41 UTC, MunBeniamin commented on .github/pull_request_template.md
> +### Summary
This should not be added on dev

2022-07-29 07:33 UTC, patriciaghitun approved these changes

2022-07-29 07:36 UTC, merged