Login request
iOSinternshipen/Internship2022TeamPatri pull request #8
Opened 2022-08-03 08:44 UTC by HVlad1

### Summary
Login request using Firebase

### Details
implemented the request
connected login UI with login API to complete the login feature

### Metadata
- Ticket link: [API]Login request (https://trello.com/c/W0kDh64P/2-api-login-request)
- Relevant design:

### Checks
- [ ] Team members are added to review the Pull Request
- [ ] Dead/unused code is deleted?
- [ ] PR does not break existing functionality
- [ ] Implementation matches the description in the story
- [ ] Images/Gifs have been added for all UI related changes

### Screenshots

2022-08-03 09:19 UTC, MunBeniamin requested changes

2022-08-03 09:19 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/AuthApiManager.swift
> +    func loginAPI(email: String?, password: String?) {
You need to pass a completion parameter here so the consumer of this method can handle its result (success or failure) and also you need to have a isLoggedIn flag that can be used outside this manager to know if the user is already loggedIn or not. (For example, on app start, if the user is already logged in you won't show the login screen anymore so you need a Bool flag to know when the user is logged in or not)

2022-08-03 11:46 UTC, MunBeniamin requested changes

2022-08-03 11:46 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Controllers/Auth/Login/LogInViewController.swift
> +                    transitionToTabbar()
This is not needed here, transition logic should be done outside of this. Think of it like someone is presenting the login screen, that someone needs to present the home-tab bar when the user is loggedin.

2022-08-03 11:46 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/AuthApiManager.swift
> +    func loginAPI(email: String?, password: String?, completion:  @escaping (Bool, Error?) -> Void) {
The completion can be just with the optional error. you don't need Bool here. The bool flag should be a public variable in the AuthApiManager, so you can access it later in the app.

2022-08-08 14:52 UTC, eduardcaragea27 approved these changes

2022-08-09 06:29 UTC, MunBeniamin commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/AuthApiManager.swift
> +                completion(error)
You have this duplicate code, you can write it only once since you are calling the completion with the same error object twice. Move this line outside of the if statement and remove the one from the else branch.

2022-08-09 06:30 UTC, MunBeniamin approved these changes
One minor change and looks good.

2022-08-09 06:30 UTC, IgnatCamelia commented on Internship2022TeamPatri/Internship2022TeamPatri/Networking/Services/AuthApiManager.swift
> +
Remove spaces

2022-08-09 07:06 UTC, iOSinternshipen approved these changes

2022-08-09 07:41 UTC, merged